server:
  port: 8090

spring:
  profiles:
    active: test
---
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: mearound
    password: mear0und
  
  redis:
    host: localhost
    password:
    port: 6379
    pool:
      max-idle: 8
      min-idle: 0
      max-active: 8
      max-wait: -1

  task:
    scheduling:
      pool.size: 10
      threadNamePrefix: DataSender
 
message:
  reader:
    template-path: data/template.txt