
spring:    
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    defer-datasource-initialization: true
    generaterate-ddl: true
    hibernate:
      ddl-auto: create-drop
      id:
        new_generator_mappings: true
        
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
        show_sql: true