
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: mearound
    password: mear0und
    listener:
      simple:
        auto-startup: false
        
  redis:
    host: localhost
    port: 6379